### ISSUE TITLE
Crash report - This Visual is not connected to a PresentationSource

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#84]
````
<?xml version="1.0"?>
<SerializableException xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ExtendedInformation>
    <HResult>-2146233079</HResult>
  </ExtendedInformation>
  <Message>This Visual is not connected to a PresentationSource.</Message>
  <Source>PresentationCore</Source>
  <StackTrace>   at System.Windows.Media.Visual.PointToScreen(Point point)
   at JuliusSweetland.OptiKey.UI.Controls.KeyboardHost.BuildPointToKeyMap() in c:\Users\Julius\Documents\GitHub\OptiKey\src\UI\Controls\KeyboardHost.cs:line 276
   at JuliusSweetland.OptiKey.UI.Controls.KeyboardHost.&lt;SubscribeToParentWindowMoves&gt;b__22(EventPattern`1 _) in c:\Users\Julius\Documents\GitHub\OptiKey\src\UI\Controls\KeyboardHost.cs:line 326
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnNextPosted(Object value)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)</StackTrace>
  <TargetSite>System.Windows.Point PointToScreen(System.Windows.Point) @ System.Windows.Media.Visual</TargetSite>
  <Type>System.InvalidOperationException</Type>
</SerializableException>
````

**Comment by JuliusSweetland** [comment]
Fixed in v2.0.8
