### ISSUE TITLE
Crash report - width and height must be non-negative (from shrinking)

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#96]
````
<?xml version="1.0"?>
<SerializableException xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ExtendedInformation>
    <HResult>-2147024809</HResult>
  </ExtendedInformation>
  <Message>Width and Height must be non-negative.</Message>
  <Source>WindowsBase</Source>
  <StackTrace>   at System.Windows.Rect..ctor(Double x, Double y, Double width, Double height)
   at JuliusSweetland.OptiKey.Services.WindowManipulationService.CalculateDockSizeAndPositionInPx(DockEdges position, DockSizes size) in c:\Users\Julius\Documents\GitHub\OptiKey\src\Services\WindowManipulationService.cs:line 599
   at JuliusSweetland.OptiKey.Services.WindowManipulationService.Shrink(ShrinkFromDirections direction, Double amountInPx) in c:\Users\Julius\Documents\GitHub\OptiKey\src\Services\WindowManipulationService.cs:line 490
   at JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.HandleFunctionKeySelectionResult(KeyValue singleKeyValue) in c:\Users\Julius\Documents\GitHub\OptiKey\src\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:line 1091
   at JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.KeySelectionResult(Nullable`1 singleKeyValue, List`1 multiKeySelection) in c:\Users\Julius\Documents\GitHub\OptiKey\src\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:line 139
   at JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.&lt;AttachServiceEventHandlers&gt;b__6(Object o, Tuple`4 tuple) in c:\Users\Julius\Documents\GitHub\OptiKey\src\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:line 112
   at JuliusSweetland.OptiKey.Services.InputService.PublishSelectionResult(Tuple`4 selectionResult) in c:\Users\Julius\Documents\GitHub\OptiKey\src\Services\InputService.cs:line 404
   at JuliusSweetland.OptiKey.Services.InputService.ProcessSelectionTrigger(TriggerSignal triggerSignal) in c:\Users\Julius\Documents\GitHub\OptiKey\src\Services\InputService.subscriptions.cs:line 185
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnNextPosted(Object value)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</StackTrace>
  <TargetSite>Void .ctor(Double, Double, Double, Double) @ System.Windows.Rect</TargetSite>
  <Type>System.ArgumentException</Type>
</SerializableException>
````

**Comment by JuliusSweetland** [comment]
Fixed in v2.0.8
